Repository My-Own-Weapon/wagu-front, pull requests merged in 2024-07, with the labels that each got.

#2 msw mocking을 이용한 main page data fetching 구현 - #1
  package.json
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/http.ts
  src/services/ApiService.ts
Labels: 👙 Feature

#47 글쓰기 기능 구현 완료 (without kakao 주소 검색)
  src/app/(post)/board/page.module.scss
  src/app/(post)/board/page.tsx
  src/app/(post)/write/page.module.scss
  src/app/(post)/write/page.tsx
  src/app/page.module.scss
  src/app/page.tsx
  src/components/BackHeader.module.scss
  src/components/BackHeader.tsx
  src/components/CategoryList.module.scss
  src/components/CategoryList.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/Post.module.scss
  src/components/Post.tsx
  src/components/ui/Button.module.scss
  src/components/ui/Button.tsx
  src/components/ui/Heading.tsx
  src/components/ui/ImageFill.tsx
  src/components/ui/InputBox.module.scss
  src/components/ui/InputBox.tsx
  src/hooks/useDragScroll.ts
  src/mocks/handlers.ts
  src/services/apiService.ts
  src/styles/globals.css
  src/styles/reset.css
  src/styles/variables/colors.scss
  src/utils/index.ts
Labels: 👙 Feature

#48 fix: url을 msw 서버로 해놨던거 백엔드 서버로 변경
  src/services/apiService.ts
Labels: 🐞 Bug

#49 글쓰기 page 구현 완료 - #45
  .eslintrc
  next.config.mjs
  public/images/bookmark.svg
  public/images/books/books.svg
  public/images/books/coral-book.svg
  public/images/books/gray-book.svg
  public/images/books/light-purple-book.svg
  public/images/books/lilac-book.svg
  public/images/books/mint-book.svg
  public/images/books/orange-book.svg
  public/images/books/purple-book.svg
  public/images/books/red-book.svg
  public/images/books/yellow-book.svg
  public/images/emoji/compass.svg
  public/images/emoji/home.svg
  public/images/emoji/pencil.svg
  public/images/emoji/sad-face.svg
  public/images/emoji/tv.svg
  public/images/emoji/vote.svg
  public/images/search-glass.svg
  src/app/(auth)/entry/page.module.scss
  src/app/(auth)/entry/page.tsx
  src/app/(auth)/login/page.module.scss
  src/app/(auth)/signup/page.module.scss
  src/app/(auth)/signup/page.tsx
  src/app/(post)/posts/[postId]/page.module.scss
  src/app/(post)/posts/[postId]/page.tsx
  src/app/(post)/write/page.module.scss
  src/app/(post)/write/page.tsx
  src/app/page.module.scss
  src/app/page.tsx
  src/components/AddressInput.module.scss
  src/components/AddressInput.tsx
  src/components/BackBtn.module.scss
  src/components/BackBtn.tsx
  src/components/BackHeader.module.scss
  src/components/BackHeader.tsx
  src/components/CategoryList.module.scss
  src/components/CategoryList.tsx
  src/components/Footer.module.scss
  src/components/Footer.tsx
  src/components/Header.module.scss
  src/components/Header.tsx
  src/components/LiveFriendsList.module.scss
  src/components/LiveFriendsList.tsx
  src/components/Post.module.scss
  src/components/Post.tsx
  src/components/UserIcon.module.scss
  src/components/UserIcon.tsx
  src/components/ui/ImageFill.tsx
  src/components/ui/InputBox.module.scss
  src/components/ui/InputBox.tsx
  src/mocks/handlers.ts
  src/services/apiService.ts
  src/services/localStorageApi.ts
  src/styles/globals.css
  src/styles/reset.css
  src/styles/variables/colors.scss
Labels: 👙 Feature

#60 session 만료시에 login page로 리다이렉팅 기능 구현 - #59
  src/app/(post)/layout.tsx
  src/app/page.tsx
  src/hooks/useCheckSession.ts
  src/services/apiService.ts
Labels: 👙 Feature

#61 [main] session 만료시에 login page로 리다이렉팅 기능 구현 - #59
  src/app/(post)/layout.tsx
  src/app/page.tsx
  src/hooks/useCheckSession.ts
  src/services/apiService.ts
Labels: 👙 Feature

#72 search page 구현 완료 - #62
  package-lock.json
  package.json
  src/app/(post)/write/page.tsx
  src/app/layout.tsx
  src/app/map/page.tsx
  src/app/page.tsx
  src/app/search/page.module.scss
  src/app/search/page.tsx
  src/app/store/[storeId]/page.tsx
  src/components/CategoryList.module.scss
  src/components/Header.module.scss
  src/components/Header.tsx
  src/components/Post.tsx
  src/components/RQProvider.tsx
  src/components/StoreCard.module.scss
  src/components/StoreCard.tsx
  src/components/UserCard.module.scss
  src/components/UserCard.tsx
  src/components/ui/ImageFill.tsx
  src/mocks/handlers.ts
  src/services/apiService.ts
  src/styles/mixins/index.scss
  src/styles/variables/colors.scss
  src/types/index.ts
Labels: 👙 Feature

#73 search page 구현 완료 - #62
  package-lock.json
  package.json
  src/app/(post)/write/page.tsx
  src/app/layout.tsx
  src/app/map/page.tsx
  src/app/page.tsx
  src/app/search/page.module.scss
  src/app/search/page.tsx
  src/app/store/[storeId]/page.tsx
  src/components/CategoryList.module.scss
  src/components/Header.module.scss
  src/components/Header.tsx
  src/components/Post.tsx
  src/components/RQProvider.tsx
  src/components/StoreCard.module.scss
  src/components/StoreCard.tsx
  src/components/UserCard.module.scss
  src/components/UserCard.tsx
  src/components/ui/ImageFill.tsx
  src/mocks/handlers.ts
  src/services/apiService.ts
  src/styles/mixins/index.scss
  src/styles/variables/colors.scss
  src/types/index.ts
Labels: 👙 Feature

#74 useEffect 의존성 배열 넣지 않은것 수정 - #62
  src/app/store/[storeId]/page.tsx
Labels: 🐞 Bug

#75 useEffect 의존성 배열 넣지 않은것 수정 - #62
  src/app/store/[storeId]/page.tsx
Labels: 🐞 Bug

#78 feat: 공유맵 마커 출력 - #46
  src/app/map/page.module.scss
  src/app/map/page.tsx
  src/app/share/page.module.scss
  src/app/share/page.tsx
Labels: 👙 Feature

#79 팔로우 기능 구현 - # 76
  .eslintrc
  src/components/UserCard.tsx
  src/services/apiService.ts
Labels: 👙 Feature

#80 [deploy] dev 브랜치에서 문제 없음을 확인 - #76
  .eslintrc
  src/components/UserCard.tsx
  src/services/apiService.ts
Labels: 📢 Deploy

#83 ShareMap 투표창 - #46
  src/app/map/page.tsx
  src/app/share/page.module.scss
  src/app/share/page.tsx
  src/components/StoreCard.tsx
  src/components/VoteUrlModal.module.scss
Labels: 👙 Feature

#85 live streaming page MVP 구현 - #81
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/live/App.css
  src/app/live/OvVideo.jsx
  src/app/live/UserVideo.css
  src/app/live/UserVideoComponent.jsx
  src/app/live/[sessionId]/page.jsx
  src/app/live/[sessionId]/page.module.scss
  src/app/live/index.css
  src/app/live/layout.tsx
  src/app/live/page.jsx
  src/app/live/page.module.scss
  src/app/live/page.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/services/apiService.ts
  src/services/localStorageApi.ts
Labels: 👙 Feature

#86 [deploy] #82 - live streaming page MVP
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/live/App.css
  src/app/live/OvVideo.jsx
  src/app/live/UserVideo.css
  src/app/live/UserVideoComponent.jsx
  src/app/live/[sessionId]/page.jsx
  src/app/live/[sessionId]/page.module.scss
  src/app/live/index.css
  src/app/live/layout.tsx
  src/app/live/page.jsx
  src/app/live/page.module.scss
  src/app/live/page.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/services/apiService.ts
  src/services/localStorageApi.ts
Labels: 📢 Deploy

#87 fix: 라이브 스트리밍 참여자가 스트리머의 카메라를 볼 수있도록 수정 - #81
  next.config.mjs
  src/app/live/UserVideoComponent.jsx
  src/app/live/[sessionId]/page.jsx
  src/services/apiService.ts
  test.jsx
Labels: 🐞 Bug

#88 [Deploy] fix - #81
  next.config.mjs
  src/app/live/UserVideoComponent.jsx
  src/app/live/[sessionId]/page.jsx
  src/services/apiService.ts
  test.jsx
Labels: 🐞 Bug

#89 [fix] 참여자는 카메라를 보이게 하지 않도록 수정 - #81
  src/app/live/App.css
  src/app/live/OvVideo.jsx
  src/app/live/UserVideo.css
  src/app/live/UserVideoComponent.jsx
  src/app/live/[sessionId]/page.jsx
  src/app/live/index.css
Labels: 🐞 Bug

#90 [deploy] live streaming - #81
  src/app/live/App.css
  src/app/live/OvVideo.jsx
  src/app/live/UserVideo.css
  src/app/live/UserVideoComponent.jsx
  src/app/live/[sessionId]/page.jsx
  src/app/live/index.css
Labels: 📢 Deploy

#91 [deploy][fix] 참여자가 참여자의 카메라가 아닌 스트리머의 카메라가 보이도록 수정 - #81
  src/app/live/[sessionId]/page.jsx
Labels: 🐞 Bug

#92 [deploy][fix] 참여자의 배열중에 0번째가 스트리머이므로 0번째만 보여지도록 수정 - #81
  src/app/live/[sessionId]/page.jsx
Labels: 🐞 Bug

#94 [Deploy] 공유 지도 배포 - #46
  src/app/map/page.module.scss
  src/app/map/page.tsx
  src/app/share/page.module.scss
  src/app/share/page.tsx
  src/components/StoreCard.tsx
  tsconfig.json
Labels: 📢 Deploy

#95 스트리머의 라이브를 시청하는 page 구현 - #81
  public/images/live/arrow_back.svg
  public/images/live/camera_switch.svg
  public/images/live/close_x.svg
  public/images/live/eye.svg
  public/images/live/send_airplain.svg
  public/images/send.svg
  src/app/live/App.css
  src/app/live/OvVideo.tsx
  src/app/live/UserVideo.css
  src/app/live/UserVideoComponent.jsx
  src/app/live/UserVideoComponent.tsx
  src/app/live/[sessionId]/page.jsx
  src/app/live/[sessionId]/page.module.scss
  src/app/live/_components/LiveHeader.module.scss
  src/app/live/_components/LiveHeader.tsx
  src/app/live/index.css
  src/app/live/layout.tsx
  src/app/live/page.tsx
  src/app/page.tsx
  src/components/LiveFriendsList.tsx
  src/components/UserIcon.module.scss
  src/components/UserIcon.tsx
  src/services/apiService.ts
  src/stores/index.tsx
  src/styles/mixins/index.scss
  src/styles/reset.css
  test.jsx
Labels: 👙 Feature

#96 [Deploy] - issue : #81, PR: #95
  public/images/live/arrow_back.svg
  public/images/live/camera_switch.svg
  public/images/live/close_x.svg
  public/images/live/eye.svg
  public/images/live/send_airplain.svg
  public/images/send.svg
  src/app/live/App.css
  src/app/live/OvVideo.tsx
  src/app/live/UserVideo.css
  src/app/live/UserVideoComponent.jsx
  src/app/live/UserVideoComponent.tsx
  src/app/live/[sessionId]/page.jsx
  src/app/live/[sessionId]/page.module.scss
  src/app/live/_components/LiveHeader.module.scss
  src/app/live/_components/LiveHeader.tsx
  src/app/live/index.css
  src/app/live/layout.tsx
  src/app/live/page.tsx
  src/app/page.tsx
  src/components/LiveFriendsList.tsx
  src/components/UserIcon.module.scss
  src/components/UserIcon.tsx
  src/services/apiService.ts
  src/stores/index.tsx
  src/styles/mixins/index.scss
  src/styles/reset.css
  test.jsx
Labels: 📢 Deploy

#98 라이브 방송 시작시에 스트리머가 방송을 시작할 가게 입력 기능 추가 - #97
  src/app/(post)/write/page.tsx
  src/app/live/page.module.scss
  src/app/live/page.tsx
  src/components/AddressInput.module.scss
  src/components/AddressInput.tsx
  src/services/apiService.ts
  src/types/index.ts
Labels: 👙 Feature

#99 [Deploy] issue: #97 / PR : #98
  src/app/(post)/write/page.tsx
  src/app/live/page.module.scss
  src/app/live/page.tsx
  src/components/AddressInput.module.scss
  src/components/AddressInput.tsx
  src/services/apiService.ts
  src/types/index.ts
Labels: 📢 Deploy

#101 [Deploy] issue: #46, PR: #100
  src/app/map/page.module.scss
  src/app/map/page.tsx
  src/app/share/page.module.scss
  src/app/share/page.tsx
  src/components/StoreCard.module.scss
  src/components/StoreCard.tsx
  src/components/VoteUrlModal.tsx
  src/styles/reset.css
Labels: 📢 Deploy

#102 [HOT FIX]: write 리뷰 자동완성 false로 변경
  src/app/(post)/write/page.tsx
  src/app/map/page.tsx
  src/app/share/page.tsx
Labels: 🐞 Bug

#105 [deploy] - issue : #104
  src/app/share/page.tsx
Labels: 🐞 Bug, 📢 Deploy

#112 새로고침시에도 session에 share map 참여자가 중복으로 등록되지 않도록 변경 - #104
  public/images/map/ping_orange.svg
  src/app/live/[sessionId]/page.jsx
  src/app/map/page.module.scss
  src/app/map/page.tsx
  src/app/share/page.tsx
  src/services/apiService.ts
  src/types/index.ts
Labels: 🔨 Refactor

#113 [deploy] PR: #112
  public/images/map/ping_orange.svg
  src/app/live/[sessionId]/page.jsx
  src/app/map/page.module.scss
  src/app/map/page.tsx
  src/app/share/page.tsx
  src/services/apiService.ts
  src/types/index.ts
Labels: 📢 Deploy

#114 share map에서 참여한 인원들이 서로의 위치를 움직이면 확인할 수 있도록 구현 - #104
  src/app/live/OvVideo.tsx
  src/app/live/UserVideoComponent.tsx
  src/app/live/[sessionId]/page.jsx
  src/app/live/page.tsx
  src/app/map/page.tsx
  src/app/share/page.tsx
  src/components/Header.tsx
  src/components/NavigationEvents.tsx
  src/hooks/useCheckSession.ts
  src/services/apiService.ts
  src/services/localStorageApi.ts
  src/types/index.ts
Labels: 👙 Feature

#115 [Deploy] Issue: #104, PR: #114
  src/app/live/OvVideo.tsx
  src/app/live/UserVideoComponent.tsx
  src/app/live/[sessionId]/page.jsx
  src/app/live/page.tsx
  src/app/map/page.tsx
  src/app/share/page.tsx
  src/components/Header.tsx
  src/components/NavigationEvents.tsx
  src/hooks/useCheckSession.ts
  src/services/apiService.ts
  src/services/localStorageApi.ts
  src/types/index.ts
Labels: 📢 Deploy

#120 main, entry 페이지 디자인 변경 - #117
  public/newDesign/categories/food_all.svg
  public/newDesign/categories/food_cafe.svg
  public/newDesign/categories/food_chiness.svg
  public/newDesign/categories/food_dessert.svg
  public/newDesign/categories/food_fastfood.svg
  public/newDesign/categories/food_japaness.svg
  public/newDesign/categories/food_korean.svg
  public/newDesign/categories/food_western.svg
  public/newDesign/categories/index.ts
  public/newDesign/logos/wagu_logo.svg
  public/newDesign/nav/home.svg
  public/newDesign/nav/index.ts
  public/newDesign/nav/live.svg
  public/newDesign/nav/map_pin.svg
  public/newDesign/nav/plus.svg
  public/newDesign/nav/search_glass.svg
  public/newDesign/nav/tropy.svg
  public/newDesign/nav/user_profile.svg
  src/app/(auth)/entry/page.module.scss
  src/app/(auth)/entry/page.tsx
  src/app/(post)/write/page.tsx
  src/app/page.module.scss
  src/app/page.tsx
  src/components/CategoryList.module.scss
  src/components/CategoryList.tsx
  src/components/Footer.module.scss
  src/components/Footer.tsx
  src/components/Header.module.scss
  src/components/Header.tsx
  src/components/LiveFriendsList.module.scss
  src/components/LiveFriendsList.tsx
  src/components/Post.module.scss
  src/components/Post.tsx
  src/components/UserIcon.module.scss
  src/components/UserIcon.tsx
  src/components/ui/Heading.module.scss
  src/components/ui/Heading.tsx
  src/components/ui/ImageFill.tsx
  src/constants/colors.ts
  src/styles/mixins/index.scss
  src/styles/variables/colors.scss
  src/styles/variables/radius.scss
Labels: 🔨 Refactor

#121 [Deploy] Issue: #117, PR: #120
  public/newDesign/categories/food_all.svg
  public/newDesign/categories/food_cafe.svg
  public/newDesign/categories/food_chiness.svg
  public/newDesign/categories/food_dessert.svg
  public/newDesign/categories/food_fastfood.svg
  public/newDesign/categories/food_japaness.svg
  public/newDesign/categories/food_korean.svg
  public/newDesign/categories/food_western.svg
  public/newDesign/categories/index.ts
  public/newDesign/logos/wagu_logo.svg
  public/newDesign/nav/home.svg
  public/newDesign/nav/index.ts
  public/newDesign/nav/live.svg
  public/newDesign/nav/map_pin.svg
  public/newDesign/nav/plus.svg
  public/newDesign/nav/search_glass.svg
  public/newDesign/nav/tropy.svg
  public/newDesign/nav/user_profile.svg
  src/app/(auth)/entry/page.module.scss
  src/app/(auth)/entry/page.tsx
  src/app/(post)/write/page.tsx
  src/app/page.module.scss
  src/app/page.tsx
  src/components/CategoryList.module.scss
  src/components/CategoryList.tsx
  src/components/Footer.module.scss
  src/components/Footer.tsx
  src/components/Header.module.scss
  src/components/Header.tsx
  src/components/LiveFriendsList.module.scss
  src/components/LiveFriendsList.tsx
  src/components/Post.module.scss
  src/components/Post.tsx
  src/components/UserIcon.module.scss
  src/components/UserIcon.tsx
  src/components/ui/Heading.module.scss
  src/components/ui/Heading.tsx
  src/components/ui/ImageFill.tsx
  src/constants/colors.ts
  src/styles/mixins/index.scss
  src/styles/variables/colors.scss
  src/styles/variables/radius.scss
Labels: 📢 Deploy

#122 게시글 상세페이지, 글쓰기 페이지 새로운 디자인 반영 및 리팩토링 - #117
  public/newDesign/X.svg
  public/newDesign/camera.svg
  public/newDesign/caret_down.svg
  public/newDesign/index.ts
  public/newDesign/nav/btn_back.svg
  public/newDesign/nav/dot-dot-dot.svg
  public/newDesign/nav/index.ts
  src/app/(post)/posts/[postId]/_components/PostHeader.module.scss
  src/app/(post)/posts/[postId]/_components/PostHeader.tsx
  src/app/(post)/posts/[postId]/page.module.scss
  src/app/(post)/posts/[postId]/page.tsx
  src/app/(post)/write/_component/CategorySelect.module.scss
  src/app/(post)/write/_component/CategorySelect.tsx
  src/app/(post)/write/page.module.scss
  src/app/(post)/write/page.tsx
  src/app/live/OvVideo.tsx
  src/app/live/UserVideoComponent.tsx
  src/app/live/[sessionId]/page.module.scss
  src/app/page.module.scss
  src/app/page.tsx
  src/app/share/page.tsx
  src/components/AddressInput.tsx
  src/components/BackHeader.module.scss
  src/components/BackHeader.tsx
  src/components/CategoryList.tsx
  src/components/Footer.module.scss
  src/components/Footer.tsx
  src/components/LiveFriendsList.tsx
  src/components/UserIcon.module.scss
  src/components/UserIcon.tsx
  src/components/ui/Heading.tsx
  src/components/ui/InputBox.module.scss
  src/components/ui/InputBox.tsx
  src/constants/categoty.ts
  src/constants/path.ts
  src/services/apiService.ts
  src/styles/globals.css
  src/styles/variables/boxSize.scss
  src/styles/variables/colors.scss
  src/types/index.ts
Labels: 🔨 Refactor

#123 [Deploy] Issue: #117, PR: #122
  public/newDesign/X.svg
  public/newDesign/camera.svg
  public/newDesign/caret_down.svg
  public/newDesign/index.ts
  public/newDesign/nav/btn_back.svg
  public/newDesign/nav/dot-dot-dot.svg
  public/newDesign/nav/index.ts
  src/app/(post)/posts/[postId]/_components/PostHeader.module.scss
  src/app/(post)/posts/[postId]/_components/PostHeader.tsx
  src/app/(post)/posts/[postId]/page.module.scss
  src/app/(post)/posts/[postId]/page.tsx
  src/app/(post)/write/_component/CategorySelect.module.scss
  src/app/(post)/write/_component/CategorySelect.tsx
  src/app/(post)/write/page.module.scss
  src/app/(post)/write/page.tsx
  src/app/live/OvVideo.tsx
  src/app/live/UserVideoComponent.tsx
  src/app/live/[sessionId]/page.module.scss
  src/app/live/_components/LiveHeader.module.scss
  src/app/live/_components/LiveHeader.tsx
  src/app/page.module.scss
  src/app/page.tsx
  src/app/share/page.tsx
  src/components/AddressInput.tsx
  src/components/BackHeader.module.scss
  src/components/BackHeader.tsx
  src/components/CategoryList.tsx
  src/components/Footer.module.scss
  src/components/Footer.tsx
  src/components/LiveFriendsList.tsx
  src/components/UserIcon.module.scss
  src/components/UserIcon.tsx
  src/components/ui/Heading.tsx
  src/components/ui/InputBox.module.scss
  src/components/ui/InputBox.tsx
  src/constants/categoty.ts
  src/constants/path.ts
  src/services/apiService.ts
  src/styles/globals.css
  src/styles/variables/boxSize.scss
  src/styles/variables/colors.scss
  src/types/index.ts
Labels: 📢 Deploy

#124 AI 리뷰 자동완성 기능 구현 완료 - #116
  src/app/(post)/write/_component/Spinner.module.scss
  src/app/(post)/write/_component/Spinnner.tsx
  src/app/(post)/write/page.module.scss
  src/app/(post)/write/page.tsx
  src/app/live/_components/LiveHeader.module.scss
  src/components/Footer.module.scss
Labels: 👙 Feature

#127 [deploy] Issue: #117, PR: #126
  next.config.mjs
  public/newDesign/map/pin_book.svg
  public/newDesign/map/pin_book_live.svg
  src/app/(auth)/login/page.module.scss
  src/app/(post)/write/_component/CategorySelect.tsx
  src/app/(post)/write/page.tsx
  src/app/live/[sessionId]/page.jsx
  src/app/map/_components/PostsOfMap.module.scss
  src/app/map/_components/PostsOfMap.tsx
  src/app/map/page.module.scss
  src/app/map/page.tsx
  src/app/page.module.scss
  src/app/page.tsx
  src/app/search/page.module.scss
  src/app/share/page.module.scss
  src/app/share/page.tsx
  src/app/store/[storeId]/page.tsx
  src/components/Footer.module.scss
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/LiveFriendsList.module.scss
  src/components/LiveFriendsList.tsx
  src/components/Post.tsx
  src/components/StoreCard.module.scss
  src/components/StoreCard.tsx
  src/components/UserCard.module.scss
  src/components/UserIcon.module.scss
  src/components/UserIcon.tsx
  src/components/ui/Heading.tsx
  src/components/ui/ImageFill.tsx
  src/constants/colors.ts
  src/mocks/handlers.ts
  src/services/apiService.ts
  src/styles/globals.css
  src/styles/mixins/index.scss
  src/styles/reset.css
  src/types/index.ts
Labels: 📢 Deploy

#128 투표 url 생성 모달 디자인 수정 - #117
  public/newDesign/index.ts
  public/newDesign/kakao.svg
  public/newDesign/share_url_hand.svg
  public/newDesign/star_ai.svg
  src/app/(post)/posts/[postId]/page.module.scss
  src/app/(post)/write/page.module.scss
  src/app/(post)/write/page.tsx
  src/app/live/_components/LiveHeader.tsx
  src/components/AddressInput.module.scss
  src/components/AddressInput.tsx
  src/components/VoteUrlModal.module.scss
  src/components/VoteUrlModal.tsx
  src/styles/mixins/index.scss
Labels: 🔨 Refactor

#129 [deploy] Issue: #117, PR: #128
  public/newDesign/index.ts
  public/newDesign/kakao.svg
  public/newDesign/share_url_hand.svg
  public/newDesign/star_ai.svg
  src/app/(post)/posts/[postId]/page.module.scss
  src/app/(post)/write/page.module.scss
  src/app/(post)/write/page.tsx
  src/app/live/_components/LiveHeader.tsx
  src/components/AddressInput.module.scss
  src/components/AddressInput.tsx
  src/components/VoteUrlModal.module.scss
  src/components/VoteUrlModal.tsx
  src/styles/mixins/index.scss
Labels: 📢 Deploy

#130 라이브 방송 bug 수정 & 투표 결과 페이지 새로운 디자인에 맞게 수정 - #117
  public/newDesign/vote/crown.svg
  public/newDesign/vote/index.ts
  public/newDesign/vote/king.svg
  src/app/live/[sessionId]/page.jsx
  src/app/live/_components/LiveHeader.tsx
  src/app/share/page.module.scss
  src/app/share/page.tsx
Labels: 🔨 Refactor, 🐞 Bug

#131 [Deploy] Issue: #117, PR: #130
  public/newDesign/vote/crown.svg
  public/newDesign/vote/index.ts
  public/newDesign/vote/king.svg
  src/app/live/[sessionId]/page.jsx
  src/app/live/_components/LiveHeader.tsx
  src/app/share/page.module.scss
  src/app/share/page.tsx
Labels: 📢 Deploy

#132 [Bug Fix] 투표결과 페이지로 못가던 버그 수정
  src/app/share/page.tsx
Labels: 🐞 Bug

#134 [deploy] Issue: #117
  public/newDesign/X_white.svg
  src/app/share/page.module.scss
  src/app/share/page.tsx
  src/components/StoreCard.module.scss
  src/components/StoreCard.tsx
Labels: 📢 Deploy

#135 로그아웃 기능 구현 - #117
  public/newDesign/sign_out.svg
  src/app/(post)/posts/[postId]/page.module.scss
  src/app/(post)/posts/[postId]/page.tsx
  src/app/share/page.module.scss
  src/app/share/page.tsx
  src/components/Header.module.scss
  src/components/Header.tsx
  src/components/StoreCard.module.scss
  src/components/StoreCard.tsx
  src/services/apiService.ts
  src/styles/variables/zIndex.scss
Labels: 👙 Feature

#136 [Deploy] 로그아웃 기능 구현 - #117
  public/newDesign/sign_out.svg
  src/app/(post)/posts/[postId]/page.module.scss
  src/app/(post)/posts/[postId]/page.tsx
  src/app/share/page.module.scss
  src/app/share/page.tsx
  src/components/Header.module.scss
  src/components/Header.tsx
  src/components/StoreCard.module.scss
  src/components/StoreCard.tsx
  src/services/apiService.ts
  src/styles/variables/zIndex.scss
Labels: 📢 Deploy

#138 user가 투표 종료시 머리에 말풍선 뜨도록 변경 - #137
  public/newDesign/nav/profile_gray.svg
  public/newDesign/nav/search_glass_gray.svg
  public/newDesign/vote/vote_done.svg
  src/app/share/page.module.scss
  src/app/share/page.tsx
  src/components/StoreCard.module.scss
  src/services/apiService.ts
  src/stores/index.tsx
Labels: 👙 Feature

#140 투표가 진행된 이후에도 선택한 store 상태 유지되도록 구현 - #137
  src/app/share/page.tsx
  src/components/StoreCard.tsx
  src/services/apiService.ts
  src/stores/index.tsx
  src/types/index.ts
Labels: 🔨 Refactor

#141 [Deploy] Issue: #137, PR: #140
  src/app/share/page.tsx
  src/components/StoreCard.tsx
  src/services/apiService.ts
  src/stores/index.tsx
  src/types/index.ts
Labels: 📢 Deploy
